CREATE TABLE webtrends.event_hi_client_update_local on cluster cluster_gio_with_shard
(   date_time Nullable(String),
    c_ip Nullable(String),
    cs_host Nullable(String),
    wt_cid Nullable(String),
    wt_co_f Nullable(String),
    wt_city Nullable(String),
    wt_mobile Nullable(String),
    wt_event Nullable(String),
    wt_ti Nullable(String),
    wt_mc_id Nullable(String),
    wt_ac Nullable(String),
    wt_ac_id Nullable(String),
    goods_id Nullable(String),
    sku_id Nullable(String),
    cs_referer Nullable(String),
    wt_es Nullable(String),
    advertype Nullable(String),
    wt_areaname Nullable(String),
    mark_id Nullable(String),
    trmnl_style Nullable(String),
    wt_aav Nullable(String),
    wt_av Nullable(String),
    date_day Nullable(String),
    prov_name Nullable(String),
    click_time Nullable(String),
    wt_prov Nullable(String),
    channelid Nullable(String),
    plat Nullable(String),
    si_x Nullable(String),
    si_n Nullable(String),
    si_s Nullable(String),
    wt_goods_id Nullable(String),
    wt_sku_id Nullable(String),
    prepare1 Nullable(String),
    cmd Nullable(String),
    os Nullable(String),
    dm Nullable(String),
    clientid Nullable(String),
    pageid Nullable(String),
    sellerid Nullable(String),
    ss_id Nullable(String),
    extendid Nullable(String),
    wt_channel_id Nullable(String),
    wt_page_id Nullable(String),
    wt_seller_id Nullable(String),
    wt_extend_id Nullable(String),
    user_agent String,
    et Nullable(String),
    next_url Nullable(String),
    envname Nullable(String),
    sv Nullable(String),
    carrieroperator Nullable(String),
    a_dc Nullable(String),
    ct Nullable(String),
    sr Nullable(String),
    vt_sid Nullable(String),
    userbrand Nullable(String),
    loginprovince Nullable(String),
    logincity Nullable(String),
    appid Nullable(String),
    channel Nullable(String),
    dcsref Nullable(String),
    ed Nullable(String),
    errcode Nullable(String),
    errmsg Nullable(String),
    serial_no Nullable(String),
    act_str_step_id Nullable(String),
    group_id Nullable(String),
    mr_id Nullable(String),
    ad_step Nullable(String),
    touch_tm Nullable(String),
    appqry Nullable(String),
    xy Nullable(String),
    sid Nullable(String),
    dcsdat String,
    event_id String,
    event_type Nullable(String),
    user_key Nullable(String),
    domain Nullable(String),
    device_model Nullable(String),
    sdk_version Nullable(String),
    location_latitude Nullable(String),
    location_longitude Nullable(String),
    platform Nullable(String),
    os_version Nullable(String),
    gio_id UInt64,
    attributes Nullable(String),
    area_id Nullable(String),
    imp_type Nullable(String),
    dt String,
    hour String,
    dcsid String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/webtrends.event_hi_client_update_local', '{replica}')
PARTITION BY (dt, hour)
ORDER BY (event_id, gio_id)
SETTINGS index_granularity = 8192, storage_policy = 'multiple_disk';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     


CREATE TABLE webtrends.event_hi_client_update_all on cluster cluster_gio_with_shard
as webtrends.event_hi_client_update_local
ENGINE = Distributed('cluster_gio_with_shard', 'webtrends', 'event_hi_client_update_local', abs(javaHash(toString(gio_id))));



CREATE INDEX index_dcsid ON webtrends.event_hi_client_update_local(dcsid) TYPE bloom_filter GRANULARITY 65536;