CREATE TABLE `ads_rpt_hachi_51006_gio_dt_hour`(
  `daytime` string COMMENT 'from deserializer', 
  `ip` string COMMENT 'from deserializer', 
  `channel_id` string COMMENT 'from deserializer', 
  `page_id` string COMMENT 'from deserializer', 
  `seller_id` string COMMENT 'from deserializer', 
  `wtdcsdat` string COMMENT 'from deserializer', 
  `wtchannelid` string COMMENT 'from deserializer', 
  `wtco_f` string COMMENT 'from deserializer', 
  `wtevent` string COMMENT 'from deserializer', 
  `wturl` string COMMENT 'from deserializer', 
  `wtmc_ev` string COMMENT 'from deserializer', 
  `wtsellerid` string COMMENT 'from deserializer', 
  `wtpageid` string COMMENT 'from deserializer', 
  `wtlast_pageid` string COMMENT 'from deserializer', 
  `wtlast_url` string COMMENT 'from deserializer', 
  `wtlast_pagename` string COMMENT 'from deserializer', 
  `wtcurrent_url` string COMMENT 'from deserializer', 
  `wtcurrent_pagename` string COMMENT 'from deserializer', 
  `wtmodule_no` string COMMENT 'from deserializer', 
  `wtmodule_name` string COMMENT 'from deserializer', 
  `wtpoint_position` string COMMENT 'from deserializer', 
  `wtmember` string COMMENT 'from deserializer', 
  `wtgoods_no` string COMMENT 'from deserializer', 
  `wtlogin_status` string COMMENT 'from deserializer', 
  `wtnext_pageid` string COMMENT 'from deserializer', 
  `wtnext_url` string COMMENT 'from deserializer', 
  `wtnext_pagename` string COMMENT 'from deserializer', 
  `wtcomponent_id` string COMMENT 'from deserializer', 
  `user_agent` string COMMENT 'from deserializer', 
  `referer` string COMMENT 'from deserializer', 
  `mobile` string COMMENT 'from deserializer', 
  `session_id` string COMMENT 'from deserializer', 
  `wtinput_sfz` string COMMENT 'from deserializer', 
  `environment` string COMMENT 'from deserializer', 
  `ip_prov` string COMMENT 'from deserializer', 
  `plat` string COMMENT 'from deserializer', 
  `si_x` string COMMENT 'from deserializer', 
  `si_n` string COMMENT 'from deserializer', 
  `si_s` string COMMENT 'from deserializer', 
  `goods_id` string COMMENT 'from deserializer', 
  `sku_id` string COMMENT 'from deserializer', 
  `prepare1` string COMMENT 'from deserializer', 
  `event_type` string COMMENT 'from deserializer', 
  `envname` string COMMENT 'from deserializer', 
  `errcode` string COMMENT 'from deserializer', 
  `errmsg` string COMMENT 'from deserializer', 
  `prov` string COMMENT 'from deserializer', 
  `city` string COMMENT 'from deserializer', 
  `mc_ev_name` string COMMENT 'from deserializer', 
  `trmnl_style` string COMMENT 'from deserializer', 
  `tbd` string COMMENT 'from deserializer', 
  `sr` string COMMENT 'from deserializer', 
  `appid` string COMMENT 'from deserializer', 
  `cid` string COMMENT 'from deserializer', 
  `userbrand` string COMMENT 'from deserializer', 
  `loginprovince` string COMMENT 'from deserializer', 
  `logincity` string COMMENT 'from deserializer', 
  `nodeid` string COMMENT 'from deserializer', 
  `tv` string COMMENT 'from deserializer', 
  `vt_f_tlh` string COMMENT 'from deserializer', 
  `vtvs` string COMMENT 'from deserializer', 
  `branch` string COMMENT 'from deserializer', 
  `dcsuri` string COMMENT 'from deserializer', 
  `ti` string COMMENT 'from deserializer', 
  `et` string COMMENT 'from deserializer', 
  `markid` string COMMENT 'from deserializer', 
  `serial_no` string COMMENT 'from deserializer', 
  `act_str_step_id` string COMMENT 'from deserializer', 
  `group_id` string COMMENT 'from deserializer', 
  `mr_id` string COMMENT 'from deserializer', 
  `ad_step` string COMMENT 'from deserializer', 
  `touch_tm` string COMMENT 'from deserializer', 
  `ed` string COMMENT 'from deserializer', 
  `xy` string COMMENT 'from deserializer', 
  `ip_city` string COMMENT 'from deserializer', 
  `wt_input_mobile` string COMMENT 'from deserializer', 
  `wt_goods_specs` string COMMENT 'from deserializer', 
  `wt_goods_price` string COMMENT 'from deserializer')
PARTITIONED BY ( 
  `dt` string, 
  `hour` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe' 
WITH SERDEPROPERTIES ( 
  'field.delim'='#_#') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://udbachdp1/user/hive/warehouse/ham.db/ads_rpt_hachi_51006_gio_dt_hour'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='true', 
  'last_modified_by'='udbac', 
  'last_modified_time'='1689131799', 
  'numFiles'='23', 
  'numRows'='67598281', 
  'rawDataSize'='0', 
  'totalSize'='2697495630', 
  'transient_lastDdlTime'='1689131799')