clickhouse-client -h 10.253.248.73 --database="olap" --receive_timeout=3600 --query="
select *
from (select event_time,
if(match(user, '^[0-9]{11}$'),user,'') AS mobile,
anonymous_user AS ck_id,
ip,
splitByString('|',ip2region(ip))[1] as ip_prov,
splitByString('|',ip2region(ip))[2] as ip_city,
attributes['\$referrer'] as referer,
decodeURLComponent(attributes['WT_event']) AS event,
splitByString('?',ifNull(decodeURLComponent(attributes['WT_es']),''))[1] as url,
decodeURLComponent(attributes['WT_si_x']) AS si_x,
decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1]) as channelid,
toDateTime(event_time) as daytime,
client_time AS cli_time,
attributes['WT_sku_id'] AS sku_id,
decodeURLComponent(attributes['WT_next_url']) AS next_url,
decodeURLComponent(attributes['WT_prov']) AS prov,
decodeURLComponent(attributes['WT_city']) AS city,
decodeURLComponent(attributes['WT_envName']) AS envName,
attributes['WT_tbd'] AS tbd,
decodeURLComponent(ifNull(user_agent,'')) as user_agent,
attributes['WT_goods_id'] AS goods_id,
decodeURLComponent(attributes['WT_cid']) as cid,
decodeURLComponent(attributes['WT_userBrand']) as userbrand,
decodeURLComponent(attributes['WT_loginProvince']) as loginprovince,
decodeURLComponent(attributes['WT_loginCity']) as logincity,
attributes['\$title'] as ti,
attributes['WT_et'] as et,
concat('https://',ifNull(domain,''),ifNull(attributes['\$path'],''),if(attributes['\$query'] is null,'','?'),cast(ifNull(attributes['\$query'],'') as String)) as es,
attributes['XY_member'] as XY_member,
attributes['XY_login_status'] as XY_login_status,
attributes['XY_environment'] as XY_environment,
attributes['XY_channelname'] as XY_channelname,
attributes['XY_pageid'] as XY_pageid,
attributes['XY_current_url'] as XY_current_url,
attributes['XY_component_id'] as XY_component_id,
attributes['XY_module_no'] as XY_module_no,
attributes['XY_module_name'] as XY_module_name,
attributes['XY_point_position'] as XY_point_position,
attributes['XY_prepare1'] as XY_prepare1,
data_source_id
from olap.event_all
where toDate(event_time)='$1'
and decodeURLComponent(attributes['WT_mc_ev'])='$2'
and data_source_id in ('a7464be8b200fe24','b9e74b9d5da046ce','b87eb8cec01051a6','b098587a3af15a25','b23efeab1461679b','a10b1f67c7d288c1','ae2308d5a08258b6','a04f0ad9925c080f','a6ba03d6884ee1c1','aa3a7b170aa41eed','a441e7427a44d390','adae9b8274a853f1','ad2e89b1010aed1e','bfe72e945deea64f','81ebc780373ee7cd','8d5d4407d1c3f6bf','abd580f08cf381e0','ba81a7647a8bed5d','8c19b47f237e28d3','a609de73d1690c0e','9c294cf845907ac1','b0839305cf5d280d','9a238b92b6612604','afdbd0f6b9a7ba30','8273883304ad70fb','86fdf7160c5cc8cc','81fab8d01c17ee89','89e7161d4a6b817f','9b50668a016469ec','bda85eeb52fb8b87','a8c29f7abfd639b4') --易数SDK
union all
select event_time,
if(match(user, '^[0-9]{11}$'),user,'') AS mobile,
anonymous_user AS ck_id,
ip,
splitByString('|',ip2region(ip))[1] as ip_prov,
splitByString('|',ip2region(ip))[2] as ip_city,
decodeURLComponent(decodeURLComponent(replaceAll(attributes['cs_referer'], '\\s+', ''))) as referer,
decodeURLComponent(attributes['WT_event']) AS event,
splitByString('?',ifNull(decodeURLComponent(attributes['WT_es']),''))[1] as url,
decodeURLComponent(attributes['WT_si_x']) AS si_x,
decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1]) as channelid,
toDateTime(event_time) as daytime,
client_time AS cli_time,
attributes['WT_sku_id'] AS sku_id,
decodeURLComponent(attributes['WT_next_url']) AS next_url,
decodeURLComponent(attributes['WT_prov']) AS prov,
decodeURLComponent(attributes['WT_city']) AS city,
decodeURLComponent(attributes['WT_envName']) AS envName,
attributes['WT_tbd'] AS tbd,
decodeURLComponent(ifNull(user_agent,'')) as user_agent,
attributes['WT_goods_id'] AS goods_id,
decodeURLComponent(attributes['WT_cid']) as cid,
decodeURLComponent(attributes['WT_userBrand']) as userbrand,
decodeURLComponent(attributes['WT_loginProvince']) as loginprovince,
decodeURLComponent(attributes['WT_loginCity']) as logincity,
decodeURLComponent(attributes['WT_ti']) as ti,
attributes['WT_et'] as et,
decodeURLComponent(attributes['WT_es']) as es,
attributes['XY_member'] as XY_member,
attributes['XY_login_status'] as XY_login_status,
attributes['XY_environment'] as XY_environment,
attributes['XY_channelname'] as XY_channelname,
attributes['XY_pageid'] as XY_pageid,
attributes['XY_current_url'] as XY_current_url,
attributes['XY_component_id'] as XY_component_id,
attributes['XY_module_no'] as XY_module_no,
attributes['XY_module_name'] as XY_module_name,
attributes['XY_point_position'] as XY_point_position,
attributes['XY_prepare1'] as XY_prepare1,
data_source_id
from olap.event_all
where toDate(event_time)='$1'
and decodeURLComponent(attributes['WT_mc_ev'])='$2'
and data_source_id in ('dcso02mhurci7zvoq6fa18exaf3_3s3i','dcsd38idvz3od4zmyowg1i6d8gx_7p1j','dcsfg7ph7uwat468njtzviizrfg_3a5k','dcs5pdfyfipmbxlfqmmciqw0a8x_8z2s','dcsz3akh3sibqou38s7guavsnr6_1w7q','dcs2skqkfpz7rtvxw6nzu4x4fgp_9w6z','dcsm3es4kqm3wtyo8gpi38qbf0j_8f4q','dcshtucfdltngkqtwvqniz0539u_2i1b','dcs8eooqrfuomftmsq6ewftia1h_6g7b','dcsxqbkupoawb04gcoq57azgdhx_0d4d','dcs6rxy80wuski0lw5qow0zt71c_8d2o','dcss2i3y89j99qo5kxpig0189i2_8m4a','dcs5pf9f1kksnaz4isjpsd7vnjo_5d3k','dcsl3qjy9cra6i10l5nz2rofjhe_3z9h','dcsc76toh4ik0az8db4ukqm84wd_4w6p','dcso43tjakd8vse5zksyuqz507q_5f8e','dcsm7pei65pvjao39ca1ams4nua_3j1d','dcsrsqxecu3ba3yqnifvv0ab9lm_9o0p','dcsppwpcwvuv2e82jv4dhm33v1c_0o1j','dcsjmisz40f127hqfku9tk6ds3n_3z7i','dcsdi06vzmk2pu9t8trixm63ctu_9b5g','dcsstwp3mj9nspzee8rta36eb9o_3r8r','dcsew4pj2u8stb71grgeavoev1w_3d2m','dcs4kes6i4udrbq7nbs1ctvql81_9m2x','dcs717bz69ty9p6a27c37oxohhf_8o8q','dcszcx0kbabmtltjrvlc1770m5q_2v6r','dcsco4d0qquihf4htc4ibo7v0ht_8j5v','dcsgl7axfbazclxywci71r3zqo9_4z6i','dcsh94u50ijasmndx4cym89ffsm_9y7c','dcstwoyw0krzaon00hpbx9hw5au_8s0b','dcs5hjggzsake53s886udkjdyei_1g3e') --博新SDK
)tb
order by event_time
limit 20000
FORMAT CSVWithNames" > $2.csv
