insert overwrite table ham_jituan.dwd_client_event_di partition (dt = '${DT}', hour = '${HH}')
select 
date_time,
c_ip,
cs_host,
regexp_replace(wt_cid, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
wt_co_f,
wt_city,
wt_mobile,
wt_event,
wt_ti,
wt_mc_id,
wt_ac,
nvl(nullif(wt_ac_id, ''),nullif(substr(regexp_extract(wt_es, 'ac_id=([0-9a-zA-z]+)', 1),0,12),'')) as wt_ac_id,
goods_id,
sku_id,
cs_referer,
wt_es,
advertype,
wt_areaname,
mark_id,
trmnl_style,
CASE WHEN wt_aav is null and wt_av is not null THEN if(instr(split(wt_av,'_')[2],'v')=1,regexp_replace(split(wt_av,'_')[2],'v',''),split(wt_av,'_')[2]) ELSE wt_aav END AS wt_aav,
wt_av,
date_day,
prov_name,
dcsdat as click_time,
wt_prov,
channelid,
plat,
regexp_replace(si_x,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_x,
regexp_replace(si_n,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_n,
regexp_replace(si_s,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_s,
wt_goods_id,
wt_sku_id,
prepare1,
cmd,
os,
dm,
clientid,
pageid,
sellerid,
ss_id,
extendid,
wt_channel_id,
wt_page_id,
wt_seller_id,
wt_extend_id,
decode_url(regexp_replace(user_agent, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
et,
decode_url(regexp_replace(next_url, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
decode_url(regexp_replace(envname, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
sv,
carrieroperator,
decode_url(regexp_replace(a_dc, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
ct,
sr,
vt_sid,
userbrand,
loginprovince,
logincity,
appid,
channel,
dcsref,
ed,
errcode,
errmsg,
serial_no,
act_str_step_id,
group_id,
mr_id,
ad_step,
touch_tm,
regexp_replace(appqry, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
xy,
sid,
dcsdat
from
(select daytime as date_time,
    ip as c_ip,
    host as cs_host,
    decode_url(query['WT.cid']) as wt_cid,
    query['WT.co_f'] as wt_co_f,
    query['WT.city'] as wt_city,
    query['WT.mobile'] as wt_mobile,
    regexp_replace(decode_url(query['WT.event']), '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') as wt_event,
    decode_url(query['WT.ti']) as wt_ti,
    query['WT.mc_id'] as wt_mc_id,
    query['WT.ac'] as wt_ac,
    query['WT.ac_id'] as wt_ac_id,
    query['WT.goods_id'] as goods_id,
    query['WT.sku_id'] as sku_id,
    decode_url(regexp_replace(referer, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')) as cs_referer,
    decode_url(regexp_replace(query['WT.es'], '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')) as wt_es,
    query['WT.adverType'] as advertype,
    decode_url(query['WT.areaName']) as wt_areaname,
    query['WT.markId'] as mark_id,
    case when dcsid='2e4p' then 'ANDROID' 
         when dcsid='9o7q' then 'IOS'
         when dcsid='2p4f' then 'H5' 
         when dcsid='5q5k' then 'MPX_App' else null end 
         as trmnl_style,
    query['WT.aav'] as wt_aav,
    CASE WHEN regexp_replace(query['WT.event'], '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') = 'sdk_loaded' AND dcsid='9o7q' THEN concat('APP_ios_v',query['WT.av'])
    WHEN regexp_replace(query['WT.event'], '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') = 'sdk_loaded' THEN regexp_replace(query['WT.av'],'APP_Android_','APP_android_')  ELSE query['WT.av'] END AS wt_av,
    translate(split(daytime, ' ')[0],'-','') as date_day,
    query['prov_name'] as prov_name,
    query['WT.prov'] as wt_prov,
    nullif(substr(regexp_extract(decode_url(query['WT.es']), 'channelId=([0-9a-zA-z]+)', 1),0,12),'') as channelid,
    query['WT.plat'] as plat,
    query['WT.si_x'] as si_x,
    decode_url(query['WT.si_n']) as si_n,
    query['WT.si_s'] as si_s,
    query['WT.goods_id'] as wt_goods_id,
    query['WT.sku_id'] as wt_sku_id,
    decode_url(query['WT.prepare1']) AS prepare1,
    query['WT.cmd'] as cmd,
    query['WT.os'] as os,
    regexp_replace(decode_url(query['WT.dm']), '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') as dm,
    decode_url(query['WT.clientID']) as clientid,
    substr(nullif(regexp_extract(decode_url(query['WT.es']), 'pageId=([0-9a-zA-z]+)', 1),''), 0, 19) as pageid,
    regexp_extract(decode_url(query['WT.es']), 'sellerId=([0-9-a-zA-z]+)',1) as sellerid,
    ss_id,
    regexp_extract(decode_url(query['WT.es']), 'extendId=([0-9-a-zA-z+-]+)',1) as extendid,
    query['WT.channelid'] as wt_channel_id,
    query['WT.pageid'] as wt_page_id,
    query['WT.sellerid'] as wt_seller_id,
    query['WT.extendid'] as wt_extend_id,
    regexp_replace(user_agent,'\\|','_') as user_agent,
        query['WT.et'] as et,
        decode_url(query['WT.next_url']) as next_url,
        decode_url(query['WT.envName']) as envname,
        query['WT.sv'] as sv,
        query['WT.carrierOperator'] as carrieroperator,
        decode_url(query['WT.a_dc']) as a_dc,
        query['WT.ct'] as ct,
        query['WT.sr'] as sr,
        query['WT.vt_sid'] as vt_sid,
        decode_url(query['WT.userBrand']) as userbrand,
        query['WT.loginProvince'] as loginprovince,
        query['WT.loginCity'] as logincity,
        query['WT.appId'] as appid,
        query['WT.channel'] as channel,
        query['WT.dcsref'] as dcsref,
        query['WT.ed'] as ed,
        query['WT.errCode'] as errcode,
        regexp_replace(decode_url(query['WT.errMsg']),'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') as errmsg,
        query['WT.serial_no'] as serial_no,
        query['WT.act_str_step_id'] as act_str_step_id,
        query['WT.group_id'] as group_id,
        query['WT.mr_id'] as mr_id,
        query['WT.ad_step'] as ad_step,
        query['WT.touch_tm'] as touch_tm,
        decode_url(query['WT.appqry']) as appqry,
        case when dcsid in ('9o7q','2e4p') then concat('{"module_no": "',decode_url(query['XY_module_no']),'","module_name": "',decode_url(query['XY_module_name']),'","point_position": "',decode_url(query['XY_point_position']),'"}') 
else decode_url(query['WT.XY']) end as xy,
        decode_url(query['WT.sid']) as sid,
        CASE WHEN query['WT.dcsdat'] is null THEN from_unixtime( cast(query['WT.ets']/1000 as int),'yyyy-MM-dd HH:mm:ss')
        ELSE from_unixtime( cast(query['WT.dcsdat']/1000 as int),'yyyy-MM-dd HH:mm:ss') END as dcsdat
from ham_jituan.ods_client_delta
where dt='${DT}' and hour='${HH}' and dcsid in ('2e4p','9o7q','2p4f','5q5k') ) as tba;