  
  truncate table ham.ads_hachi_jzyy_xtb2_51008_local on cluster cluster_gio_with_shard
  
  #h5重复工单表
  bill_no Nullable(String), 
  imei Nullable(String), 
  cookie Nullable(String), 
  prov_id Nullable(String), 
  prov_name Nullable(String), 
  city_name Nullable(String), 
  channel_id Nullable(String), 
  c_ip Nullable(String), 
  cs_host Nullable(String), 
  trmnl_style Nullable(String), 
  app_version Nullable(String), 
  sys_version Nullable(String), 
  create_date Nullable(String), 
  create_datetime Nullable(String), 
  click_datetime Nullable(String), 
  serial_id Nullable(String), 
  start_time Nullable(String), 
  down_time Nullable(String), 
  status Nullable(String), 
  issue_range Nullable(String), 
  if_own_develop Nullable(String), 
  frequency Nullable(String), 
  area_name Nullable(String), 
  area_location Nullable(String), 
  link_referer Nullable(String), 
  link_current Nullable(String), 
  url Nullable(String), 
  issue_id Nullable(String), 
  mark_id Nullable(String), 
  mark_name Nullable(String), 
  mark_type Nullable(String), 
  advertype Nullable(String), 
  wt_event Nullable(String), 
  wt_ti Nullable(String), 
  wt_mc_id Nullable(String), 
  wt_ac Nullable(String), 
  wt_ac_id Nullable(String), 
  goods_id Nullable(String), 
  sku_id Nullable(String), 
  editor_prov_name Nullable(String), 
  mark_mode Nullable(String), 
  if_prov_page Nullable(String), 
  icon_code Nullable(String), 
  login_type Nullable(String), 
  is_webtends Nullable(String), 
  if_safe_audit Nullable(String), 
  editor Nullable(String), 
  editor_phone_num Nullable(String), 
  pro_company Nullable(String), 
  template_id Nullable(String), 
  analy_type Nullable(String), 
  conf_chan Nullable(String), 
  point_type Nullable(String), 
  area_type Nullable(String), 
  plat Nullable(String), 
  si_x Nullable(String), 
  si_n Nullable(String), 
  si_s Nullable(String), 
  wt_goods_id Nullable(String), 
  wt_sku_id Nullable(String), 
  prepare1 Nullable(String), 
  pageid Nullable(String), 
  sellerid Nullable(String), 
  extendid Nullable(String), 
  wt_channel_id Nullable(String), 
  wt_page_id Nullable(String), 
  wt_seller_id Nullable(String), 
  wt_extend_id Nullable(String),
  dt String,
  hour String


#字段
bill_no,imei,cookie,prov_id,prov_name,city_name,channel_id,c_ip,cs_host,trmnl_style,app_version,sys_version,create_date,create_datetime,click_datetime,serial_id,start_time,down_time,status,issue_range,if_own_develop,frequency,area_name,area_location,link_referer,link_current,url,issue_id,mark_id,mark_name,mark_type,advertype,wt_event,wt_ti,wt_mc_id,wt_ac,wt_ac_id,goods_id,sku_id,editor_prov_name,mark_mode,if_prov_page,icon_code,login_type,is_webtends,if_safe_audit,editor,editor_phone_num,pro_company,template_id,analy_type,conf_chan,point_type,area_type,plat,si_x,si_n,si_s,wt_goods_id,wt_sku_id,prepare1,pageid,sellerid,extendid,wt_channel_id,wt_page_id,wt_seller_id,wt_extend_id

ads_hachi_jzyy_xtb2_51008

drop table ham.ads_hachi_jzyy_xtb2_51008_all on cluster cluster_gio_with_shard

#分布式表——本地
CREATE TABLE ham.ads_hachi_jzyy_xtb2_51008_local on cluster cluster_gio_with_shard
(
  bill_no Nullable(String), 
  imei Nullable(String), 
  cookie Nullable(String), 
  prov_id Nullable(String), 
  prov_name Nullable(String), 
  city_name Nullable(String), 
  channel_id Nullable(String), 
  c_ip Nullable(String), 
  cs_host Nullable(String), 
  trmnl_style Nullable(String), 
  app_version Nullable(String), 
  sys_version Nullable(String), 
  create_date Nullable(String), 
  create_datetime Nullable(String), 
  click_datetime Nullable(String), 
  serial_id Nullable(String), 
  start_time Nullable(String), 
  down_time Nullable(String), 
  status Nullable(String), 
  issue_range Nullable(String), 
  if_own_develop Nullable(String), 
  frequency Nullable(String), 
  area_name Nullable(String), 
  area_location Nullable(String), 
  link_referer Nullable(String), 
  link_current Nullable(String), 
  url Nullable(String), 
  issue_id Nullable(String), 
  mark_id Nullable(String), 
  mark_name Nullable(String), 
  mark_type Nullable(String), 
  advertype Nullable(String), 
  wt_event Nullable(String), 
  wt_ti Nullable(String), 
  wt_mc_id Nullable(String), 
  wt_ac Nullable(String), 
  wt_ac_id Nullable(String), 
  goods_id Nullable(String), 
  sku_id Nullable(String), 
  editor_prov_name Nullable(String), 
  mark_mode Nullable(String), 
  if_prov_page Nullable(String), 
  icon_code Nullable(String), 
  login_type Nullable(String), 
  is_webtends Nullable(String), 
  if_safe_audit Nullable(String), 
  editor Nullable(String), 
  editor_phone_num Nullable(String), 
  pro_company Nullable(String), 
  template_id Nullable(String), 
  analy_type Nullable(String), 
  conf_chan Nullable(String), 
  point_type Nullable(String), 
  area_type Nullable(String), 
  plat Nullable(String), 
  si_x Nullable(String), 
  si_n Nullable(String), 
  si_s Nullable(String), 
  wt_goods_id Nullable(String), 
  wt_sku_id Nullable(String), 
  prepare1 Nullable(String), 
  pageid Nullable(String), 
  sellerid Nullable(String), 
  extendid Nullable(String), 
  wt_channel_id Nullable(String), 
  wt_page_id Nullable(String), 
  wt_seller_id Nullable(String), 
  wt_extend_id Nullable(String),
  dt String,
  hour String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/ham.ads_hachi_jzyy_xtb2_51008_local1', '{replica}')
ORDER BY (hour)
SETTINGS index_granularity = 8192, storage_policy = 'multiple_disk';


#分布式表——视图
CREATE TABLE ham.ads_hachi_jzyy_xtb2_51008_all on cluster cluster_gio_with_shard
as ham.ads_hachi_jzyy_xtb2_51008_local
ENGINE = Distributed('cluster_gio_with_shard', 'ham', 'ads_hachi_jzyy_xtb2_51008_local', rand());