
select 
case when match(user, '^[0-9]{11}$') then user when match(user, '.*==$') and length(user)=24 then aes2_function(base64Decode(user)) end AS mobile,
anonymous_user AS ck_id,
session  AS ss_id,
ip,
--
--改成一个
splitByString('|',ip2region(case when countSubstrings(ip,'.')=3 or countSubstrings(ip,':')=7 then ip else '0|0' end))[1] as ip_prov,
splitByString('|',ip2region(case when countSubstrings(ip,'.')=3 or countSubstrings(ip,':')=7 then ip else '0|0' end))[2] as ip_city,
--处理
attributes['$reffer'] as referer_s,
attributes[''] as referer,
decodeURLComponent(attributes['WT_event']) AS event,
--太长
if(position(domain,'.')>0,if(match(domain,'^[0-9]+[.]+[0-9]+[.]+[0-9]+[.]+[0-9]+$'),concat('http://',ifNull(domain,''),ifNull(attributes[''],'')),concat('https://',ifNull(domain,''),ifNull(attributes[''],''))),domain) as url,
decodeURLComponent(decodeURLComponent(attributes['WT_si_n'])) AS si_n,
decodeURLComponent(attributes['WT_si_s']) AS si_s,
decodeURLComponent(attributes['WT_si_x']) AS si_x,
if(wtchannelid = '--',nullif(substr(extract(decodeURLComponent(attributes['']), 'channelId=([0-9a-zA-z]+)'),1,12),''),wtchannelid) as channel_id,
if(wtpageid = '--',substr(nullif(extract(decodeURLComponent(attributes['']), 'pageId=([0-9a-zA-z]+)'),''), 1, 19),wtpageid) as page_id,
decodeURLComponent(attributes['WT_input_xm']) AS input_xm,
decodeURLComponent(attributes['WT.input_sfz'])  AS input_sfz,
decodeURLComponent(attributes['WT.input_dz']) AS input_dz,
decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
if(wtsellerid ='--',extract(decodeURLComponent(attributes['']), 'sellerId=([0-9-a-zA-z]+)'),wtsellerid) as seller_id,
attributes['WT_last_pageid'] AS last_pageid,
attributes['WT_module_no'] AS module_no,
decodeURLComponent(attributes['WT_point_position']) AS point_position,
decodeURLComponent(attributes['WT_member']) AS member,
decodeURLComponent(attributes['WT_goods_no']) AS goods_no,
attributes['WT_login_status'] AS login_status,
decodeURLComponent(attributes['WT_input_dq']) AS input_dq,
decodeURLComponent(attributes['WT_input_buymobile']) AS input_buymobile,
toDateTime(event_time) as daytime,
toUnixTimestamp(client_time) * 1000 + CAST(splitByString('.', CAST(client_time, 'String'))[2], 'Int') AS cli_time,
attributes['WT_last_url'] AS last_url,
decodeURLComponent(attributes['WT_last_pagename']) AS last_pagename,
attributes['WT_current_url'] AS current_url,
decodeURLComponent(attributes['WT_current_pagename']) AS current_pagename,
decodeURLComponent(attributes['WT_module_name']) AS module_name,
attributes['WT_next_pageid'] AS next_pageid,
decodeURLComponent(attributes['WT_next_url']) AS next_url,
decodeURLComponent(attributes['WT_next_pagename']) AS next_pagename,
attributes['WT_component_id'] AS component_id,
decodeURLComponent(attributes['WT_input_mobile']) as input_mobile,
attributes['WT_touchcode'] AS touchcode,
attributes['WT_tpl'] AS tpl,
decodeURLComponent(attributes['WT_branch']) as branch,
concat(url,ifNull(concat('?',attributes['']),'')) as complete_url,
attributes['WT_point_name'] AS point_name,
attributes['WT_component_name'] AS component_name,
attributes['WT_environment'] AS environment,
decodeURLComponent(attributes['WT_plat']) AS plat,
attributes['WT_sku_id'] AS sku_id,
decodeURLComponent(attributes['WT_prepare1']) as prepare1,
decodeURLComponent(attributes['WT_event_type']) AS event_type2,
decodeURLComponent(attributes['WT_envName']) AS envName,
decodeURLComponent(attributes['WT_errCode']) AS errCode,
decodeURLComponent(attributes['WT_errMsg']) AS errMsg,
decodeURLComponent(attributes['WT_prov']) AS prov,
decodeURLComponent(attributes['WT_city']) AS city,
decodeURLComponent(attributes['WT_mc_ev_name']) AS mc_ev_name,
data_source_id as trmnl_style,
'--' AS tbd,
ifNull(attributes['WT_dcsdat'],'') AS dcsdat,
decodeURLComponent(ifNull(user_agent,'')),
attributes['WT_goods_id'] AS goods_id,
attributes['screen'] AS sr, 
attributes['WT_appId'] AS appid,
decodeURLComponent(attributes['WT_cid']) as cid,
decodeURLComponent(attributes['WT_userBrand']) as userbrand,
decodeURLComponent(attributes['WT_loginProvince']) as loginprovince,
decodeURLComponent(attributes['WT_loginCity']) as logincity,
attributes['WT_nodeId'] as nodeid,
attributes['WT_tv'] as tv,
attributes['WT_vt_f_tlh'] as vt_f_tlh,
'--' as vtvs,
'--' as mark33,
attributes[''] as dcsuri,
attributes[''] as ti,
event_key as et, 
attributes['WT_markId'] as markid,
attributes['WT_serial_no'] as serial_no,
attributes['WT_act_str_step_id'] as act_str_step_id,
attributes['WT_group_id'] as group_id,
attributes['WT_mr_id'] as mr_id,
attributes['WT_ad_step'] as ad_step,
attributes['WT_touch_tm'] as touch_tm,
attributes[''] as ed,
decodeURLComponent(attributes['WT_XY']) as xy,
decodeURLComponent(attributes['WT_vt_sid']) as vt_sid, 
concat(url,ifNull(concat('?',attributes['']),'')) as es,
decodeURLComponent(attributes['WT_sellerid']) AS wtsellerid,
decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1]) as wtchannelid,
decodeURLComponent(attributes['WT_pageid'])  as wtpageid,
event_id,
user_key,
domain,
device_model,
sdk_version,
location_latitude,
location_longitude,
platform,
os_version,
gio_id,
attributes,
toDate(event_time) as dt,
LPAD(toString(toHour(event_time)), 2, '0') AS hour,
data_source_id
FROM olap.event_all
WHERE dt = '2023-08-18'
and hour = '07'
and event_type = 'custom_event' 
and data_source_id in ('a1f48d9ff4f42571','b508a809cbbddd0b')
and attributes['WT_av'] is null
; │
