CREATE TABLE webtrends.event_flink_dcslog_51006_local on cluster cluster_gio_with_shard
(
    mobile Nullable(String),
    ck_id Nullable(String),
    ss_id Nullable(String),
    ip Nullable(String),
    ip_prov Nullable(String),
    ip_city Nullable(String),
    referer Nullable(String),
    event Nullable(String),
    url Nullable(String),
    si_n Nullable(String),
    si_s Nullable(String),
    si_x Nullable(String),
    channel_id Nullable(String),
    page_id Nullable(String),
    input_xm Nullable(String),
    input_sfz Nullable(String),
    input_dz Nullable(String),
    mc_ev Nullable(String),
    seller_id Nullable(String),
    last_pageid Nullable(String),
    module_no Nullable(String),
    point_position Nullable(String),
    member Nullable(String),
    goods_no Nullable(String),
    login_status Nullable(String),
    input_dq Nullable(String),
    input_buymobile Nullable(String),
    daytime Nullable(String),
    cli_time Nullable(String),
    last_url Nullable(String),
    last_pagename Nullable(String),
    current_url Nullable(String),
    current_pagename Nullable(String),
    module_name Nullable(String),
    next_pageid Nullable(String),
    next_url Nullable(String),
    next_pagename Nullable(String),
    component_id Nullable(String),
    input_mobile Nullable(String),
    touchcode Nullable(String),
    tpl Nullable(String),
    branch Nullable(String),
    complete_url Nullable(String),
    point_name Nullable(String),
    component_name Nullable(String),
    environment Nullable(String),
    plat Nullable(String),
    sku_id Nullable(String),
    prepare1 Nullable(String),
    event_type Nullable(String),
    envname Nullable(String),
    errcode Nullable(String),
    errmsg Nullable(String),
    prov Nullable(String),
    city Nullable(String),
    mc_ev_name Nullable(String),
    trmnl_style Nullable(String),
    tbd Nullable(String),
    dcsdat String,
    user_agent String,
    goods_id Nullable(String),
    sr Nullable(String),
    appid Nullable(String),
    cid Nullable(String),
    userbrand Nullable(String),
    loginprovince Nullable(String),
    logincity Nullable(String),
    nodeid Nullable(String),
    tv Nullable(String),
    vt_f_tlh Nullable(String),
    vtvs Nullable(String),
    mark33 Nullable(String),
    dcsuri Nullable(String),
    ti Nullable(String),
    et Nullable(String),
    markid Nullable(String),
    serial_no Nullable(String),
    act_str_step_id Nullable(String),
    group_id Nullable(String),
    mr_id Nullable(String),
    ad_step Nullable(String),
    touch_tm Nullable(String),
    ed Nullable(String),
    xy Nullable(String),
    vt_sid Nullable(String),
    es Nullable(String),
    wtsellerid Nullable(String),
    wtchannelid Nullable(String),
    wtpageid Nullable(String),
    event_id String,
    user_key Nullable(String),
    domain Nullable(String),
    device_model Nullable(String),
    sdk_version Nullable(String),
    location_latitude Nullable(String),
    location_longitude Nullable(String),
    platform Nullable(String),
    os_version Nullable(String),
    gio_id String,
    attributes Nullable(String),
    dt String,
    hour String,
    dcsid String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/webtrends.event_flink_dcslog_51006_local', '{replica}')
PARTITION BY (dt, hour)
ORDER BY (dcsdat, user_agent, event_id, gio_id)
SETTINGS index_granularity = 8192, storage_policy = 'multiple_disk';


CREATE TABLE webtrends.event_flink_dcslog_51006_all on cluster cluster_gio_with_shard
as webtrends.event_flink_dcslog_51006_local
ENGINE = Distributed('cluster_gio_with_shard', 'webtrends', 'event_flink_dcslog_51006_local', rand());