set hive.exec.compress.output=true;
set mapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec;


insert overwrite table ham_jituan.ads_hachi_jzyy_xtb2_51007_dt_hour partition (dt = '${DT}', hour = '${HH}')
select
date_time,
c_ip,
cs_host,
regexp_replace(wt_cid,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
wt_co_f,
wt_city,
wt_mobile,
wt_event,
regexp_replace(wt_ti,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
wt_mc_id,
wt_ac,
wt_ac_id,
goods_id,
sku_id,
regexp_replace(cs_referer,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
decode_url(regexp_replace(decode_url(wt_es),'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
advertype,
wt_areaname,
mark_id,
trmnl_style,
wt_aav,
wt_av,
date_day,
prov_name,
click_time,
wt_prov,
channelid,
plat,
regexp_replace(si_x,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_x,
regexp_replace(si_n,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_n,
regexp_replace(si_s,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|','') as si_s,
wt_goods_id,
wt_sku_id,
prepare1,
pageid,
sellerid,
extendid,
wt_channel_id,
wt_page_id,
wt_seller_id,
wt_extend_id,
regexp_replace(user_agent, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') as user_agent,
cmd,
os,
regexp_replace(dm, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '') as dm,
sv,
decode_url(regexp_replace(a_dc, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
ct,
sr,
vt_sid,
userbrand,
loginprovince,
logincity,
appid,
channel,
et,
ed,
decode_url(regexp_replace(envname, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
decode_url(regexp_replace(next_url, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', '')),
errcode,
regexp_replace(errmsg,'\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
serial_no,
act_str_step_id,
group_id,
mr_id,
ad_step,
touch_tm,
regexp_replace(appqry, '\\n+|\\r+|(\\n\\r)+|\\t+|\\|', ''),
xy,
sid
from ham_jituan.dwd_client_event_di 
where dt='${DT}'
and hour = '${HH}'
;
