select
toDateTime(event_time) as daytime,
ip,
ifNull(attributes['WT_dcsdat'],'') AS dcsdat,
if(decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1]) = '--',nullif(substr(extract(decodeURLComponent(attributes['$query']), 'channelId=([0-9a-zA-z]+)'),1,12),''),decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1])) as channel_id,
anonymous_user AS ck_id,
decodeURLComponent(attributes['WT_vt_sid']) as vt_sid,
decodeURLComponent(attributes['WT_event']) AS event,
concat('https://',domain,attributes['$path'],'?',attributes['$query']) as es,
decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
decodeURLComponent(attributes['WT_next_url']) AS next_url,
decodeURLComponent(ifNull(user_agent,'')),
coalesce(case when match(user, '^[0-9]{11}$') then user end, first_value(case when match(user, '^[0-9]{11}$') then user end)
                  OVER (PARTITION BY anonymous_user
                      ORDER BY event_time ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)) AS mobile,
decodeURLComponent(attributes['WT_si_x']) AS si_x,
decodeURLComponent(decodeURLComponent(attributes['WT_si_n'])) AS si_n,
decodeURLComponent(attributes['WT_si_s']) AS si_s,
attributes['WT_goods_id'] AS goods_id,
attributes['WT_sku_id'] AS sku_id,
decodeURLComponent(attributes['WT_envName']) AS envName,
decodeURLComponent(attributes['WT_errCode']) AS errCode,
decodeURLComponent(attributes['WT_errMsg']) AS errMsg,
decodeURLComponent(attributes['WT_prov']) AS prov,
decodeURLComponent(attributes['WT_city']) AS city,
data_source_id as trmnl_style,
attributes['screen'] AS sr,
attributes['WT_appId'] AS appid,
decodeURLComponent(attributes['WT_cid']) as cid,
decodeURLComponent(attributes['WT_userBrand']) as userbrand,
decodeURLComponent(attributes['WT_loginProvince']) as loginprovince,
decodeURLComponent(attributes['WT_loginCity']) as logincity,
attributes['WT_nodeId'] as nodeid,
attributes['WT_tv'] as tv,
attributes['WT_vt_f_tlh'] as vt_f_tlh,
'--' as vtvs,
decodeURLComponent(attributes['WT_branch']) as branch,
attributes['$path'] as dcsuri,
attributes['$title'] as ti,
event_key as et, 
attributes['WT_markId'] as markid,
attributes['WT_serial_no'] as serial_no,
attributes['WT_act_str_step_id'] as act_str_step_id,
attributes['WT_group_id'] as group_id,
attributes['WT_mr_id'] as mr_id,
attributes['WT_ad_step'] as ad_step,
attributes['WT_touch_tm'] as touch_tm,
attributes['$duration'] as ed,
decodeURLComponent(attributes['WT_XY']) as xy
from olap.event_all
where toDate(event_time) = '2023-04-17'
and data_source_id = '8273883304ad70fb'
and attributes['$path'] = '/inner/waph52019/portal/welfare'