INSERT INTO webtrends.event_hi_dcslog_update_all
SELECT
  aes_function(COALESCE(CASE WHEN match(user, '^[0-9]{11}$') THEN user END, FIRST_VALUE(CASE WHEN match(user, '^[0-9]{11}$') THEN user END)
      OVER (PARTITION BY anonymous_user ORDER BY event_time ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), '')) AS mobile,
  anonymous_user AS ck_id,
  session AS ss_id,
  ip,
  splitByString('|', ip2region(ip))[1] AS ip_prov,
  splitByString('|', ip2region(ip))[2] AS ip_city,
  attributes['$reffer'] AS referer,
  decodeURLComponent(attributes['WT_event']) AS event,
  CASE WHEN position(domain, '.') > 0 THEN
    IF(match(domain, '^[0-9]+[.]+[0-9]+[.]+[0-9]+[.]+[0-9]+$'), CONCAT('http://', IFNULL(domain, ''), IFNULL(attributes['$path'], '')), CONCAT('https://', IFNULL(domain, ''), IFNULL(attributes['$path'], '')))
  ELSE
    domain
  END AS url,
  decodeURLComponent(decodeURLComponent(attributes['WT_si_n'])) AS si_n,
  decodeURLComponent(attributes['WT_si_s']) AS si_s,
  decodeURLComponent(attributes['WT_si_x']) AS si_x,
  IF(wtchannelid = '--', NULLIF(substr(extract(decodeURLComponent(attributes['$query']), 'channelId=([0-9a-zA-z]+)'), 1, 12), ''), wtchannelid) AS channel_id,
  IF(wtpageid = '--', substr(NULLIF(extract(decodeURLComponent(attributes['$query']), 'pageId=([0-9a-zA-z]+)'), ''), 1, 19), wtpageid) AS page_id,
  decodeURLComponent(attributes['WT_input_xm']) AS input_xm,
  decodeURLComponent(attributes['WT.input_sfz']) AS input_sfz,
  decodeURLComponent(attributes['WT.input_dz']) AS input_dz,
  decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
  IF(wtsellerid = '--', extract(decodeURLComponent(attributes['$query']), 'sellerId=([0-9-a-zA-z]+)'), wtsellerid) AS seller_id,
  attributes['WT_last_pageid'] AS last_pageid,
  attributes['WT_module_no'] AS module_no,
  decodeURLComponent(attributes['WT_point_position']) AS point_position,
  decodeURLComponent(attributes['WT_member']) AS member,
  decodeURLComponent(attributes['WT_goods_no']) AS goods_no,
  attributes['WT_login_status'] AS login_status,
  decodeURLComponent(attributes['WT_input_dq']) AS input_dq,
  decodeURLComponent(attributes['WT_input_buymobile']) AS input_buymobile,
  toDateTime(event_time) AS daytime,
  toUnixTimestamp(client_time) * 1000 + CAST(splitByString('.', CAST(client_time, 'String'))[2], 'Int') AS cli_time,
  attributes['WT_last_url'] AS last_url,
  decodeURLComponent(attributes['WT_last_pagename']) AS last_pagename,
  attributes['WT_current_url'] AS current_url,
  decodeURLComponent(attributes['WT_current_pagename']) AS current_pagename,
  decodeURLComponent(attributes['WT_page_type']) AS page_type,
  attributes['WT_domain'] AS domain,
  decodeURLComponent(attributes['WT_link_name']) AS link_name,
  attributes['WT_form_name'] AS form_name,
  decodeURLComponent(attributes['WT_form_fields']) AS form_fields,
  attributes['WT_status'] AS status,
  attributes['WT_lang'] AS lang,
  attributes['WT_mobile'] AS mobile,
  attributes['WT_touchcode'] AS touchcode,
  attributes['WT_tpl'] AS tpl,
  decodeURLComponent(attributes['WT_branch']) AS branch,
  CONCAT(url, IFNULL(CONCAT('?', attributes['$query']), '')) AS complete_url,
  attributes['WT_point_name'] AS point_name,
  attributes['WT_component_name'] AS component_name,
  attributes['WT_environment'] AS environment,
  decodeURLComponent(attributes['WT_plat']) AS plat,
  attributes['WT_sku_id'] AS sku_id,
  decodeURLComponent(attributes['WT_prepare1']) AS prepare1,
  decodeURLComponent(attributes['WT_event_type']) AS event_type,
  decodeURLComponent(attributes['WT_envName']) AS envName,
  decodeURLComponent(attributes['WT_errCode']) AS errCode,
  decodeURLComponent(attributes['WT_errMsg']) AS errMsg,
  decodeURLComponent(attributes['WT_prov']) AS prov,
  decodeURLComponent(attributes['WT_city']) AS city,
  decodeURLComponent(attributes['WT_mc_ev_name']) AS mc_ev_name,
  data_source_id AS trmnl_style,
  '--' AS tbd,
  IFNULL(attributes['WT_dcsdat'], '') AS dcsdat,
  decodeURLComponent(IFNULL(user_agent, '')),
  attributes['WT_goods_id'] AS goods_id,
  attributes['screen'] AS sr,
  attributes['WT_appId'] AS appid,
  decodeURLComponent(attributes['WT_cid']) AS cid,
  decodeURLComponent(attributes['WT_userBrand']) AS userbrand,
  decodeURLComponent(attributes['WT_loginProvince']) AS loginprovince,
  decodeURLComponent(attributes['WT_loginCity']) AS logincity,
  attributes['WT_nodeId'] AS nodeid,
  attributes['WT_tv'] AS tv,
  attributes['WT_vt_f_tlh'] AS vt_f_tlh,
  '--' AS vtvs,
  '--' AS mark33,
  attributes['$path'] AS dcsuri,
  decodeURLComponent(COALESCE(attributes['WT_ti'], attributes['$title'])) AS wt_ti,
  event_key AS et,
  attributes['WT_markId'] AS markid,
  attributes['WT_serial_no'] AS serial_no,
  attributes['WT_act_str_step_id'] AS act_str_step_id,
  attributes['WT_group_id'] AS group_id,
  attributes['WT_mr_id'] AS mr_id,
  attributes['WT_ad_step'] AS ad_step,
  attributes['WT_touch_tm'] AS touch_tm,
  attributes['$duration'] AS ed,
  decodeURLComponent(attributes['WT_XY']) AS xy,
  decodeURLComponent(attributes['WT_vt_sid']) AS vt_sid,
  CONCAT(url, IFNULL(CONCAT('?', attributes['$query']), '')) AS es,
  decodeURLComponent(attributes['WT_sellerid']) AS wtsellerid,
  decodeURLComponent(splitByString('%', CAST(IFNULL(attributes['WT_channelid'], '') AS String))[1]) AS wtchannelid,
  decodeURLComponent(attributes['WT_pageid']) AS wtpageid,
  event_id,
  user_key,
  domain,
  device_model,
  sdk_version,
  location_latitude,
  location_longitude,
  platform,
  os_version,
  gio_id,
  attributes,
  toDate(event_time) AS dt,
  IF(CAST(attributes['WT_lt'] AS Int64) >= 1000, CAST(attributes['WT_lt'] AS Int64), 1000) AS lt
FROM webtrends.event_hi_dcslog_raw_all
WHERE toDate(event_time) BETWEEN toDate('2023-01-01') AND toDate('2023-06-30')
