select 
toDateTime(event_time)  as date_time,
attributes['c_ip'] as c_ip,
attributes['cs_host'] as cs_host,
decodeURLComponent(attributes['WT_cid']) as wt_cid,
anonymous_user AS  wt_co_f,
attributes['WT_city'] wt_city,
if(match(user, '^1[3-9]\\d{9}$'), user, NULL) as wt_mobile,
decodeURLComponent(attributes['WT_event']) as wt_event,
attributes['$title'] as wt_ti,
attributes['WT_mc_id'] as wt_mc_id,
attributes['WT_ac'] as wt_ac,
CASE WHEN attributes['WT_ac_id'] is not null THEN ifNull(nullif(splitByString('%', cast(attributes['WT_ac_id'] AS String))[1], ''), nullif(substring(extract(wt_es, 'ac_id=([0-9a-zA-z]+)'), 1, 12), '')) else nullif(substring(extract(wt_es, 'ac_id=([0-9a-zA-z]+)'), 1, 12), '') end AS wt_ac_id,
attributes['WT_goods_id'] as goods_id,
attributes['WT_sku_id'] as sku_id,
attributes['$reffer'] as cs_referer,
concat(if(position(domain,'.')>0,if(match(domain,'^[0-9]+[.]+[0-9]+[.]+[0-9]+[.]+[0-9]+$'),concat('http://',ifNull(domain,''),ifNull(attributes['$path'],'')),concat('https://',ifNull(domain,''),ifNull(attributes['$path'],''))),domain),ifNull(concat('?',attributes['$query']),'')) as wt_es,
attributes['WT_adverType'] as advertype,
decodeURLComponent(attributes['WT_areaname']) as wt_areaname,
attributes['WT_markId'] as mark_id,
'a1f48d9ff4f42571' AS trmnl_style,
CASE WHEN attributes['WT_aav'] is null AND attributes['WT_av'] is not null THEN if(position(splitByString('_', cast(attributes['WT_av'] AS String))[3], 'v') = 1 , CASE WHEN attributes['WT_av'] is null THEN '' else replace(splitByString('_', cast(attributes['WT_av'] AS String))[3], 'v', '') end, splitByString('_', cast(attributes['WT_av'] AS String))[3]) ELSE attributes['WT_aav'] END AS wt_aav,
CASE WHEN wt_event = 'sdk_loaded' AND data_source_id='9o7q' THEN concat('APP_ios_v',attributes['WT_av']) 
WHEN wt_event = 'sdk_loaded' THEN replace(attributes['WT_av'],'APP_Android_','APP_android_')  
ELSE attributes['WT_av'] END  AS wt_av,
toYYYYMMDD(event_time) date_day,
decodeURLComponent(attributes['WT_prov_name'])  prov_name,
dcsdat  as click_time,
attributes['WT_prov'] as wt_prov,
nullif(substr(extract(decodeURLComponent(attributes['$query']), 'channelId=([0-9a-zA-z]+)'),1,12),'') as channelid,
attributes['WT_plat'] plat,
decodeURLComponent(attributes['WT_si_x']) as si_x,
decodeURLComponent(attributes['WT_si_n']) as si_n,
decodeURLComponent(attributes['WT_si_s']) as si_s,
attributes['WT_goods_id'] wt_goods_id,
attributes['WT_sku_id'] wt_sku_id,
attributes['prepare1'] prepare1,
attributes['WT_cmd'] cmd,
attributes['WT_os'] os,
attributes['WT_dm'] as dm,
client_version as clientid,
substr(nullif(extract(decodeURLComponent(attributes['$query']), 'pageId=([0-9a-zA-z]+)'),''), 1, 19)as  pageid,
extract(decodeURLComponent(attributes['$query']), 'sellerId=([0-9-a-zA-z]+)') as sellerid,
session AS ss_id,
nullif(extract(decodeURLComponent(attributes['$query']), 'extendId=([0-9-a-zA-z+-]+)'),'') as extendid,
attributes['WT_channelid'] wt_channel_id,
attributes['WT_pageid'] wt_page_id,
attributes['WT_sellerid'] wt_seller_id,
attributes['WT_extendid'] wt_extend_id,
replaceAll(ifNull(user_agent,''),'\\|','_') as  user_agent,
attributes['WT_et'] et,
decodeURLComponent(attributes['WT_next_url']) next_url,
decodeURLComponent(attributes['WT_envName']) envname,
attributes['WT_sv'] sv,
attributes['WT_carrierOperator'] carrierOperator,
decodeURLComponent(attributes['WT_a_dc']) a_dc,
attributes['WT_ct'] ct,
attributes['screen'] sr,
attributes['WT_vt_sid'] vt_sid,
decodeURLComponent(attributes['WT_userbrand']) userbrand,
attributes['WT_loginProvince'] loginprovince,
attributes['WT_loginCity'] logincity,
attributes['WT_appId'] appid,
attributes['WT_channel'] channel,
attributes['WT_dcsref'] dcsref,
attributes['$duration'] ed,
attributes['WT_errCode'] as errcode,
decodeURLComponent(attributes['WT_errMsg']) as errmsg,
attributes['WT_serial_no'] serial_no,
attributes['WT_act_str_step_id'] act_str_step_id,
attributes['WT_group_id'] group_id,
attributes['WT_mr_id'] mr_id,
attributes['WT_ad_step'] ad_step,
attributes['WT_touch_tm'] touch_tm,
decodeURLComponent(attributes['WT_appqry']) as appqry,
decodeURLComponent(attributes['WT_XY']) as xy,
decodeURLComponent(attributes['WT_sid']) as sid,
ifNull((CASE WHEN attributes['WT_dcsdat'] is null THEN attributes['WT_ets']
      ELSE attributes['WT_dcsdat'] END),'') as dcsdat,
event_id,
event_type,
user_key,
domain,
device_model,
sdk_version,
location_latitude,
location_longitude,
platform,
os_version,
gio_id,
attributes,
toDate(event_time) as dt,
if(length(cast(toHour(toDateTime(event_time)) as String))=1,concat('0',cast(toHour(toDateTime(event_time)) as String)),cast(toHour(toDateTime(event_time)) as String)) as hour,
data_source_id as dcsid
from olap.event_all 
WHERE dt = '${DT}'
and hour = '${Hour}'
and data_source_id = 'a1f48d9ff4f42571'
;
"
