set hive.vectorized.execution.enabled = false;
set hive.exec.compress.output=true;
set mapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec;

INSERT OVERWRITE TABLE ham.ads_rpt_hachi_51010
select
regexp_replace(daytime,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(ip,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(cli_time,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(channel_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(ck_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(vt_sid,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(event,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(es,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(mc_ev,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(next_url,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(user_agent,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(mobile,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(si_x,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(si_n,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(si_s,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(goods_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(sku_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(envname,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(errcode,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(errmsg,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(prov,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(city,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(trmnl_style,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(sr,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(appid,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(cid,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(userbrand,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(loginprovince,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(logincity,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(nodeid,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(tv,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(vt_f_tlh,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(vtvs,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(branch,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(dcsuri,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(ti,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(et,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(markid,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(serial_no,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(act_str_step_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(group_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(mr_id,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(ad_step,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(touch_tm,'\\n+|\\r+|(\\n\\r)+|\\t','')
,regexp_replace(ed,'\\n+|\\r+|(\\n\\r)+|\\t','')
,decode_url(regexp_replace(xy,'\\n+|\\r+|(\\n\\r)+|\\t',''))
,regexp_replace(prepare1,'\\n+|\\r+|(\\n\\r)+|\\t','')
from dwd_dcslog_event_di
where dt='${DT}'
and trmnl_style in ('3s3i','7p1j','3a5k','8z2s','1w7q','9w6z','8f4q','2i1b','6g7b','0d4d','8d2o','8m4a','5d3k','3z9h','4w6p','5f8e','3j1d','9o0p','0o1j','3z7i','9b5g','3r8r','3d2m','9m2x','8o8q','2v6r','8j5v','4z6i','9y7c','8s0b','1g3e','7c2d')
;
