#!/bin/sh
DT=$1
Hour=$2

clickhouse-client -h 10.253.248.73 -n --receive_timeout=3600  --query="
insert into table webtrends.event_51010_tmp_all
select 
case when match(user, '^[0-9]{11}$') then user when match(user, '.*==$') and length(user)=24 then aes2_function(base64Decode(user)) end AS mobile,
--case when match(user, '^[0-9]{11}$') then user when match(user, '.*==$') then decrypt('aes-128-ecb',base64Decode(user), '9e5702ead4d643fd') end AS mobile,
--user AS mobile,
attributes['ck_id'] AS ck_id,
decodeURLComponent(concat(attributes['ck_id'],':',attributes['WT_vtvs']))  AS ss_id,
ip,
splitByString('|',ip2region(case when countSubstrings(ip,'.')=3 or countSubstrings(ip,':')=7 then ip else '0|0' end))[1] as ip_prov,
splitByString('|',ip2region(case when countSubstrings(ip,'.')=3 or countSubstrings(ip,':')=7 then ip else '0|0' end))[2] as ip_city,
replaceRegexpAll(decodeURLComponent(decodeURLComponent(attributes['cs_referer'])), '\\s+', '') as referer,
decodeURLComponent(attributes['WT_event']) AS event,
splitByString('?',ifNull(decodeURLComponent(attributes['WT_es']),''))[1] as url,
decodeURLComponent(decodeURLComponent(attributes['WT_si_n'])) AS si_n,
decodeURLComponent(attributes['WT_si_s']) AS si_s,
decodeURLComponent(attributes['WT_si_x']) AS si_x,
if(wtchannelid = '--',attributes['channelId'],wtchannelid) as channel_id,
if(wtpageid = '--',attributes['pageId'],wtpageid) as page_id,
decodeURLComponent(attributes['WT_input_xm']) AS input_xm,
decodeURLComponent(attributes['WT_input_sfz'])  AS input_sfz,
decodeURLComponent(attributes['WT_input_dz']) AS input_dz,
decodeURLComponent(attributes['WT_mc_ev']) AS mc_ev,
if(wtsellerid ='--',attributes['sellerId'],wtsellerid) as seller_id,
attributes['WT_last_pageid'] AS last_pageid,
attributes['WT_module_no'] AS module_no,
decodeURLComponent(attributes['WT_point_position']) AS point_position,
decodeURLComponent(attributes['WT_member']) AS member,
decodeURLComponent(attributes['WT_goods_no']) AS goods_no,
attributes['WT_login_status'] AS login_status,
decodeURLComponent(attributes['WT_input_dq']) AS input_dq,
decodeURLComponent(attributes['WT_input_buymobile']) AS input_buymobile,
toDateTime(event_time) as daytime,
ifNull(attributes['WT_dcsdat'],'') AS cli_time,
attributes['WT_last_url'] AS last_url,
decodeURLComponent(attributes['WT_last_pagename']) AS last_pagename,
attributes['WT_current_url'] AS current_url,
decodeURLComponent(attributes['WT_current_pagename']) AS current_pagename,
decodeURLComponent(attributes['WT_module_name']) AS module_name,
attributes['WT_next_pageid'] AS next_pageid,
decodeURLComponent(attributes['WT_next_url']) AS next_url,
decodeURLComponent(attributes['WT_next_pagename']) AS next_pagename,
attributes['WT_component_id'] AS component_id,
decodeURLComponent(attributes['WT_input_mobile']) as input_mobile,
attributes['WT_touchcode'] AS touchcode,
attributes['WT_tpl'] AS tpl,
decodeURLComponent(attributes['WT_branch']) as branch,
decodeURLComponent(attributes['WT_es']) as complete_url,
attributes['WT_point_name'] AS point_name,
attributes['WT_component_name'] AS component_name,
attributes['WT_environment'] AS environment,
decodeURLComponent(attributes['WT_plat']) AS plat,
attributes['WT_sku_id'] AS sku_id,
decodeURLComponent(attributes['WT_prepare1']) as prepare1,
decodeURLComponent(attributes['WT_event_type']) AS event_type,
decodeURLComponent(attributes['WT_envName']) AS envName,
decodeURLComponent(attributes['WT_errCode']) AS errCode,
decodeURLComponent(attributes['WT_errMsg']) AS errMsg,
decodeURLComponent(attributes['WT_prov']) AS prov,
decodeURLComponent(attributes['WT_city']) AS city,
decodeURLComponent(attributes['WT_mc_ev_name']) AS mc_ev_name,
case   when (data_source_id  ='dcscx966fo4l7j258ag0s874n_3w7x' or data_source_id = 'aa410d5cd21666f5')then 'H5' 
         when data_source_id ='dcs47s4etp4l7jyla4pkwq3ox_5m9b' or data_source_id='dcsg4yobzk4bgdw3x3i02ujp5_7e9m' then '小程序'
         when data_source_id ='dcschlc2kl4bgdodrniom31n2_5i5n' then '公众号'
         else splitByString('_',ifNull(data_source_id,''))[2] end 
         as trmnl_style,
attributes['WT_tbd'] AS tbd,
ifNull(attributes['WT_dcsdat'],'') AS dcsdat,
decodeURLComponent(ifNull(user_agent,'')),
attributes['WT_goods_id'] AS goods_id,
attributes['WT_sr'] AS sr,
attributes['WT_appId'] AS appid,
decodeURLComponent(attributes['WT_cid']) as cid,
decodeURLComponent(attributes['WT_userBrand']) as userbrand,
decodeURLComponent(attributes['WT_loginProvince']) as loginprovince,
decodeURLComponent(attributes['WT_loginCity']) as logincity,
attributes['WT_nodeId'] as nodeid,
attributes['WT_tv'] as tv,
attributes['WT_vt_f_tlh'] as vt_f_tlh,
attributes['WT_vtvs'] as vtvs,
'' as mark33,
decodeURLComponent(attributes['dcsuri']) as dcsuri,
decodeURLComponent(attributes['WT_ti']) as ti,
attributes['WT_et'] as et,
attributes['WT_markId'] as markid,
attributes['WT_serial_no'] as serial_no,
attributes['WT_act_str_step_id'] as act_str_step_id,
attributes['WT_group_id'] as group_id,
attributes['WT_mr_id'] as mr_id,
attributes['WT_ad_step'] as ad_step,
attributes['WT_touch_tm'] as touch_tm,
attributes['WT_ed'] as ed,
decodeURLComponent(attributes['WT_XY']) as xy,
decodeURLComponent(attributes['WT_vt_sid']) as vt_sid, 
decodeURLComponent(attributes['WT_es']) as es,
decodeURLComponent(attributes['WT_sellerid']) AS wtsellerid,
decodeURLComponent(splitByString('%',cast(ifNull(attributes['WT_channelid'],'') as String))[1]) as wtchannelid,
decodeURLComponent(attributes['WT_pageid'])  as wtpageid,
event_id,
user_key,
domain,
device_model,
sdk_version,
location_latitude,
location_longitude,
platform,
os_version,
gio_id,
attributes,
toDate(event_time) as dt,
if(length(cast(toHour(toDateTime(event_time)) as String))=1,concat('0',cast(toHour(toDateTime(event_time)) as String)),cast(toHour(toDateTime(event_time)) as String)) as hour,
data_source_id
FROM olap.event_all
WHERE dt = '${DT}'
and hour = '${Hour}'
and data_source_id in ('dcs49gd2jh65d2sj1tsa4rky3fd_7c2d','dcso02mhurci7zvoq6fa18exaf3_3s3i','dcsd38idvz3od4zmyowg1i6d8gx_7p1j','dcsfg7ph7uwat468njtzviizrfg_3a5k','dcs5pdfyfipmbxlfqmmciqw0a8x_8z2s','dcsz3akh3sibqou38s7guavsnr6_1w7q','dcs2skqkfpz7rtvxw6nzu4x4fgp_9w6z','dcsm3es4kqm3wtyo8gpi38qbf0j_8f4q','dcshtucfdltngkqtwvqniz0539u_2i1b','dcs8eooqrfuomftmsq6ewftia1h_6g7b','dcsxqbkupoawb04gcoq57azgdhx_0d4d','dcs6rxy80wuski0lw5qow0zt71c_8d2o','dcss2i3y89j99qo5kxpig0189i2_8m4a','dcs5pf9f1kksnaz4isjpsd7vnjo_5d3k','dcsl3qjy9cra6i10l5nz2rofjhe_3z9h','dcsc76toh4ik0az8db4ukqm84wd_4w6p','dcso43tjakd8vse5zksyuqz507q_5f8e','dcsm7pei65pvjao39ca1ams4nua_3j1d','dcsrsqxecu3ba3yqnifvv0ab9lm_9o0p','dcsppwpcwvuv2e82jv4dhm33v1c_0o1j','dcsjmisz40f127hqfku9tk6ds3n_3z7i','dcsdi06vzmk2pu9t8trixm63ctu_9b5g','dcsstwp3mj9nspzee8rta36eb9o_3r8r','dcsew4pj2u8stb71grgeavoev1w_3d2m','dcs4kes6i4udrbq7nbs1ctvql81_9m2x','dcs717bz69ty9p6a27c37oxohhf_8o8q','dcszcx0kbabmtltjrvlc1770m5q_2v6r','dcsco4d0qquihf4htc4ibo7v0ht_8j5v','dcsgl7axfbazclxywci71r3zqo9_4z6i','dcsh94u50ijasmndx4cym89ffsm_9y7c','dcstwoyw0krzaon00hpbx9hw5au_8s0b','dcs5hjggzsake53s886udkjdyei_1g3e','dcsxx79x7scb3ch36d1admiccz8_3n9u','dcsykjbxwjtpr16z9ky13i6yf2c_6c9w','dcsfbtwtw133n16xt52e80xmz5a_2n3t','dcs6ikkxfmix0pkmx13fat96kj4_3p3y')
;
" 
'dcs49gd2jh65d2sj1tsa4rky3fd_7c2d','dcso02mhurci7zvoq6fa18exaf3_3s3i','dcsd38idvz3od4zmyowg1i6d8gx_7p1j','dcsfg7ph7uwat468njtzviizrfg_3a5k','dcs5pdfyfipmbxlfqmmciqw0a8x_8z2s','dcsz3akh3sibqou38s7guavsnr6_1w7q','dcs2skqkfpz7rtvxw6nzu4x4fgp_9w6z','dcsm3es4kqm3wtyo8gpi38qbf0j_8f4q','dcshtucfdltngkqtwvqniz0539u_2i1b','dcs8eooqrfuomftmsq6ewftia1h_6g7b','dcsxqbkupoawb04gcoq57azgdhx_0d4d','dcs6rxy80wuski0lw5qow0zt71c_8d2o','dcss2i3y89j99qo5kxpig0189i2_8m4a','dcs5pf9f1kksnaz4isjpsd7vnjo_5d3k','dcsl3qjy9cra6i10l5nz2rofjhe_3z9h','dcsc76toh4ik0az8db4ukqm84wd_4w6p','dcso43tjakd8vse5zksyuqz507q_5f8e','dcsm7pei65pvjao39ca1ams4nua_3j1d','dcsrsqxecu3ba3yqnifvv0ab9lm_9o0p','dcsppwpcwvuv2e82jv4dhm33v1c_0o1j','dcsjmisz40f127hqfku9tk6ds3n_3z7i','dcsdi06vzmk2pu9t8trixm63ctu_9b5g','dcsstwp3mj9nspzee8rta36eb9o_3r8r','dcsew4pj2u8stb71grgeavoev1w_3d2m','dcs4kes6i4udrbq7nbs1ctvql81_9m2x','dcs717bz69ty9p6a27c37oxohhf_8o8q','dcszcx0kbabmtltjrvlc1770m5q_2v6r','dcsco4d0qquihf4htc4ibo7v0ht_8j5v','dcsgl7axfbazclxywci71r3zqo9_4z6i','dcsh94u50ijasmndx4cym89ffsm_9y7c','dcstwoyw0krzaon00hpbx9hw5au_8s0b','dcs5hjggzsake53s886udkjdyei_1g3e','dcsxx79x7scb3ch36d1admiccz8_3n9u','dcsykjbxwjtpr16z9ky13i6yf2c_6c9w','dcsfbtwtw133n16xt52e80xmz5a_2n3t','dcs6ikkxfmix0pkmx13fat96kj4_3p3y'